image: elixir

before_script:
  - mix local.hex --force
  - mix deps.get

stages:
  - test

check_format:
  stage: test
  script:
    - mix format --check-formatted --dry-run

run_tests:
  stage: test
  script:
    - mix test
